version: "3.9"

services:
  web:
    build: .
    command: python vms/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/vms
    ports:
      - "8000:8000"
    links:
      - db
    environment:
      - DJANGO_SETTINGS_MODULE=vms.settings

  db:
    image: postgres:9.6.3
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
